server:
  port: 8083

spring:
  application:
    name: Customer-Service
  datasource:
    url: jdbc:mysql://localhost:3306/auction_api
    username: root
    password:
  zipkin:
    base-url: http://127.0.0.1:9411/zipkin/
  jpa:
    hibernate:
      ddl-auto: update


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost